import { Metadata } from 'next'
import RootLayoutClient from './RootLayoutClient'
import '@/styles/globals.css'

import { Web3Provider } from './providers/WagmiProvider'

export const metadata: Metadata = {
  title: 'tokenizer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <RootLayoutClient>
          <Web3Provider>{children}</Web3Provider>
        </RootLayoutClient>
      </body>
    </html>
  )
}
